services:
  # ----------------------------
  # Laravel App
  # ----------------------------
  app:
    build: .
    volumes:
      - ./src:/var/www         # Mount your project source code
      - vendor_data:/var/www/vendor  # Persistent vendor folder
    networks:
      - project2_net
      - shared_db_net

  # ----------------------------
  # Nginx
  # ----------------------------
  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    depends_on:
      - app
    networks:
      - project2_net

# ----------------------------
# Volumes
# ----------------------------
volumes:
  vendor_data:

# ----------------------------
# Networks
# ----------------------------
networks:
  project2_net:
    driver: bridge
  shared_db_net:
    external: true
